/*
class MyException 
{
public static void main(String[] args)
{
try
{
System.out.println(10/0);
}
catch(ArithmeticException ie)
{
System.out.println(10/0);
}
finally
{
System.out.println("Finally block of code ");
}
System.out.println("Rest code");
}
}

class MyException 
{
public static void main(String[] args)
{
try
{
System.out.println(10/0);
}
catch(ArithmeticException ie)
{
System.out.println(10/2);
}
finally
{
System.out.println(10/0);
}
System.out.println("Rest code");
}
}

class MyException 
{
public static void main(String[] args)
{
try
{
System.out.println(10/0);
}
finally
{
System.out.println("Finally blockk of code ");
}
System.out.println("Rest code");
}
}
*/

